# Generated by Django 5.2.7 on 2025-11-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g. 1kg, 500g, 2lb', max_length=50),
        ),
    ]
