# Generated by Django 4.2 on 2025-11-03 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('flavor', models.CharField(max_length=100)),
                ('weight', models.CharField(choices=[('0.5 lbs', '0.5 lbs'), ('1 lbs', '1 lbs'), ('2 lbs', '2 lbs'), ('3 lbs', '3+ lbs')], max_length=10)),
                ('message', models.TextField()),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='custom_designs/')),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('replied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g. 1lbs, 500g, 2lb', max_length=50),
        ),
        migrations.DeleteModel(
            name='CustomCake',
        ),
    ]
