# Generated by Django 4.2 on 2025-11-03 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_customcakerequest_alter_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakerequest',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 11, 3), help_text='When do you want your cake?'),
            preserve_default=False,
        ),
    ]
